name: Sample Workflow
#this shows how to use the Reusable SFDX Deployment Action

on: 
  workflow_dispatch

jobs:
  Deploy:
    
    uses: Charush-Devgan/Reusable-SFDX-Deployment-Github-Action/.github/workflows/Reusable SFDX Deployment Action.yml@main
    with:
      ref: ${{ github.ref }}
      run-tests: true
      check-only: true
      env: DEV
      secrets: inherit
